# Generated by Django 4.2.14 on 2026-07-17 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_portal', '0007_alter_prenatalvisit_bp_diastolic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('expected_gestational_week', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed')], default='upcoming', max_length=10)),
                ('linked_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hospital_portal.prenatalvisit')),
                ('mother', models.ForeignKey(limit_choices_to={'role': 'mother'}, on_delete=django.db.models.deletion.CASCADE, related_name='anc_visit_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expected_date'],
            },
        ),
        migrations.CreateModel(
            name='UltrasoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('dating', 'Dating / Viability Scan (6-9 wks)'), ('nt_dual', 'NT Scan + Dual Marker (11-13+6 wks)'), ('anomaly', 'Anomaly Scan / TIFFA (18-22 wks)'), ('growth', 'Growth Scan (28+ wks)')], max_length=20)),
                ('scan_date', models.DateField()),
                ('intrauterine_confirmed', models.BooleanField(blank=True, null=True)),
                ('number_of_fetuses', models.PositiveIntegerField(blank=True, null=True)),
                ('fetal_cardiac_activity', models.BooleanField(blank=True, null=True)),
                ('nuchal_translucency_mm', models.FloatField(blank=True, null=True)),
                ('dual_marker_risk', models.CharField(blank=True, max_length=20)),
                ('placenta_position', models.CharField(blank=True, max_length=100)),
                ('liquor_status', models.CharField(blank=True, max_length=100)),
                ('head_circumference_mm', models.FloatField(blank=True, null=True)),
                ('abdominal_circumference_mm', models.FloatField(blank=True, null=True)),
                ('femur_length_mm', models.FloatField(blank=True, null=True)),
                ('estimated_gestational_age_weeks', models.FloatField(blank=True, null=True)),
                ('estimated_fetal_weight_g', models.FloatField(blank=True, null=True)),
                ('estimated_fetal_weight_percentile', models.FloatField(blank=True, help_text='If known -- used to flag growth restriction (<10th percentile)', null=True)),
                ('fetal_movement_normal', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultrasound_reports', to='hospital_portal.prenatalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('trimester', models.IntegerField(choices=[(0, 'Any'), (1, '1st Trimester'), (2, '2nd Trimester'), (3, '3rd Trimester')], default=0)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('severe_min', models.FloatField(blank=True, null=True)),
                ('severe_max', models.FloatField(blank=True, null=True)),
                ('flag_message_low', models.CharField(blank=True, max_length=255)),
                ('flag_message_high', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Lab Test Reference Range',
                'unique_together': {('test_code', 'trimester')},
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=150)),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('is_flagged', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, max_length=10)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='hospital_portal.prenatalvisit')),
            ],
            options={
                'indexes': [models.Index(fields=['test_code'], name='anc_clinica_test_co_d1615c_idx')],
            },
        ),
    ]
