# Generated by Django 4.2.14 on 2026-07-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anc_clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lab', 'Lab'), ('ultrasound', 'Ultrasound')], max_length=12)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=150)),
                ('applies_to', models.CharField(blank=True, choices=[('first_visit', 'First visit only'), ('follow_up', 'Follow-up (until ~20-28 weeks)'), ('third_trimester', 'Third trimester (28+ weeks)')], max_length=20)),
                ('week_min', models.FloatField(blank=True, null=True)),
                ('week_max', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'code'], name='anc_clinica_categor_f2874d_idx')],
            },
        ),
    ]
