# Generated by Django 4.2.14 on 2026-07-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_rag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeChunk',
        ),
    ]
