# Generated by Django 4.2.14 on 2026-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness_rag', '0002_delete_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='safety_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='structured_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
