# Generated by Django 4.2.14 on 2026-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mother', 'Mother'), ('data_entry', 'Data Entry Operator'), ('admin', 'Admin')], default='mother', max_length=20),
        ),
    ]
