# Generated by Django 4.2.14 on 2026-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mother', 'Mother'), ('doctor', 'Doctor'), ('data_entry', 'Data Entry Operator'), ('admin', 'Admin')], default='mother', max_length=20),
        ),
    ]
