# Generated by Django 4.2.14 on 2026-07-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_week', models.PositiveSmallIntegerField()),
                ('fetal_development_note', models.TextField(blank=True)),
                ('maternal_changes_note', models.TextField(blank=True)),
                ('maternal_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=15)),
                ('hospital_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['gestational_week'],
                'unique_together': {('user', 'gestational_week')},
            },
        ),
    ]
