# Generated by Django 4.2.14 on 2026-07-09 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_portal', '0003_medication'),
        ('tracker', '0002_personalcheckin_delete_weeklyupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalcheckin',
            options={'ordering': ['-logged_at']},
        ),
        migrations.RenameField(
            model_name='personalcheckin',
            old_name='created_at',
            new_name='logged_at',
        ),
        migrations.RemoveField(
            model_name='personalcheckin',
            name='gestational_week',
        ),
        migrations.RemoveField(
            model_name='personalcheckin',
            name='visit_date',
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hospital_portal.medication')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
