# Generated by Django 4.2.14 on 2026-07-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_alter_personalcheckin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBabyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(unique=True)),
                ('size_comparison', models.CharField(blank=True, help_text="e.g. 'about the size of a corn cob'", max_length=100)),
                ('fact_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['week'],
            },
        ),
        migrations.AddField(
            model_name='personalcheckin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_images/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='DoctorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_answered', '-created_at'],
            },
        ),
    ]
