# Generated by Django 4.2.14 on 2026-07-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_weeklybabyfact_personalcheckin_image_doctorquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybabyfact',
            options={'ordering': ['start_week']},
        ),
        migrations.RemoveField(
            model_name='weeklybabyfact',
            name='week',
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='end_week',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='start_week',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='size_comparison',
            field=models.CharField(blank=True, help_text="e.g. 'about the size of a lime'", max_length=100),
        ),
    ]
