# Generated by Django 4.2.14 on 2026-07-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_weeklybabyfact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklybabyfact',
            options={'ordering': ['start_week'], 'verbose_name': 'Weekly Baby Development', 'verbose_name_plural': 'Weekly Baby Development'},
        ),
        migrations.RemoveField(
            model_name='weeklybabyfact',
            name='fact_text',
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='average_length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='average_weight_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='baby_development',
            field=models.JSONField(blank=True, default=list, help_text='List of developmental milestones'),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='exercise_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='fun_fact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='image_name',
            field=models.CharField(blank=True, help_text='Example: week24.png', max_length=100),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='mother_changes',
            field=models.JSONField(blank=True, default=list, help_text='List of maternal body changes'),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='nutrition_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='title',
            field=models.CharField(default='True', help_text='Dashboard heading', max_length=200),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='trimester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')], null=True),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='warning_signs',
            field=models.JSONField(blank=True, default=list, help_text='List of symptoms requiring medical care'),
        ),
        migrations.AddField(
            model_name='weeklybabyfact',
            name='weekly_milestone',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='end_week',
            field=models.PositiveSmallIntegerField(help_text='Ending gestational week'),
        ),
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='size_comparison',
            field=models.CharField(help_text='Example: About the size of an avocado', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='start_week',
            field=models.PositiveSmallIntegerField(help_text='Starting gestational week'),
        ),
    ]
