# Generated by Django 4.2.14 on 2026-07-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_weeklybabyfact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='title',
            field=models.CharField(help_text='Dashboard heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='weeklybabyfact',
            name='trimester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Trimester'), (2, 'Second Trimester'), (3, 'Third Trimester')], default=1),
            preserve_default=False,
        ),
    ]
