# Generated by Django 4.2.14 on 2026-07-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of tag keys, e.g. ['tired', 'anxious']"),
        ),
    ]
