# Generated by Django 4.2.14 on 2026-07-05 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
