# Generated by Django 4.2.14 on 2026-07-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0002_alter_healthprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='allergy_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'No restriction'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_gestational_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
    ]
