# Generated by Django 4.2.14 on 2026-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0003_healthprofile_allergies_healthprofile_allergy_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='drinks_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='edd_is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='live_births_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='previous_complications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='previous_complications_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='previous_pregnancies_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='smokes',
            field=models.BooleanField(default=False),
        ),
    ]
