# Generated by Django 4.2.14 on 2026-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0004_healthprofile_drinks_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Select your blood group'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', "I don't know")], max_length=10),
        ),
    ]
