# Generated by Django 4.2.14 on 2026-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0005_alter_healthprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='pre_pregnancy_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
