# Generated by Django 4.2.14 on 2026-07-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0006_healthprofile_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='delivery_date',
        ),
    ]
