# Generated by Django 4.2.14 on 2026-07-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_profile', '0007_remove_healthprofile_delivery_date'),
        ('health_profile', '0008_add_date_of_birth'),
    ]

    operations = [
    ]
