# Generated by Django 4.2.14 on 2026-07-09 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrimesterNarrativeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count_at_generation', models.PositiveIntegerField(default=0)),
                ('narrative_text', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trimester_narrative_cache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
