# Generated by Django 4.2.14 on 2026-07-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trimester_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimesternarrativecache',
            name='narrative_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
