# Generated by Django 4.2.14 on 2026-07-07 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('gestational_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maternal_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=15)),
                ('fundal_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fetal_heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fetal_movement', models.CharField(blank=True, choices=[('active', 'Active'), ('reduced', 'Reduced'), ('none', 'None reported')], max_length=10)),
                ('urine_protein', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus1', '+1'), ('plus2', '+2'), ('plus3', '+3')], max_length=10)),
                ('urine_glucose', models.CharField(blank=True, choices=[('negative', 'Negative'), ('trace', 'Trace'), ('plus1', '+1'), ('plus2', '+2'), ('plus3', '+3')], max_length=10)),
                ('hemoglobin_g_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fetal_position', models.CharField(blank=True, choices=[('cephalic', 'Cephalic (head-down)'), ('breech', 'Breech'), ('transverse', 'Transverse'), ('not_assessed', 'Not assessed')], max_length=15)),
                ('edema', models.CharField(blank=True, choices=[('none', 'None'), ('mild_hands_feet', 'Mild -- hands/feet'), ('mild_face', 'Mild -- face'), ('severe', 'Severe')], max_length=20)),
                ('doctor_notes', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse', 'data_entry']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_entered', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(limit_choices_to={'role': 'mother'}, on_delete=django.db.models.deletion.CASCADE, related_name='prenatal_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.DeleteModel(
            name='ClinicalRecord',
        ),
    ]
