# Generated by Django 4.2.14 on 2026-07-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_portal', '0003_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='food_instruction',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food'), ('empty', 'Empty Stomach'), ('any', 'Any Time')], default='after', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('supplement', 'Supplement'), ('vitamin', 'Vitamin'), ('antibiotic', 'Antibiotic'), ('painkiller', 'Pain Relief'), ('other', 'Other')], default='supplement', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('custom', 'Custom Time')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='purpose',
            field=models.CharField(blank=True, help_text='Reason for prescribing (e.g. Iron deficiency)', max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Optional reminder time', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='route',
            field=models.CharField(choices=[('oral', 'Oral'), ('injection', 'Injection'), ('iv', 'Intravenous'), ('topical', 'Topical'), ('other', 'Other')], default='oral', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(help_text='e.g. 500 mg, 5 mL', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of doses per day'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(help_text='Medication name (e.g. Ferrous Sulfate)', max_length=150),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional instructions from the doctor'),
        ),
    ]
