# Generated by Django 4.2.14 on 2026-07-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_portal', '0004_medication_food_instruction_and_more'),
        ('hospital_portal', '0005_add_vitals_and_flagging'),
    ]

    operations = [
    ]
