# Generated by Django 4.2.14 on 2026-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_portal', '0006_merge_20260717_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenatalvisit',
            name='bp_diastolic',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Auto-parsed from blood_pressure', null=True),
        ),
        migrations.AlterField(
            model_name='prenatalvisit',
            name='bp_systolic',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Auto-parsed from blood_pressure', null=True),
        ),
    ]
