# Generated by Django 4.2.14 on 2026-07-04 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('PSS10', 'Perceived Stress Scale (10 items)'), ('EPDS', 'Edinburgh Postnatal Depression Scale'), ('GAD7', 'Generalized Anxiety Disorder (7 items)')], max_length=10)),
                ('answers', models.JSONField(help_text='Ordered list of per-question integer scores')),
                ('total_score', models.PositiveSmallIntegerField(editable=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], editable=False, max_length=10)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
