# Generated by Django 4.2.14 on 2026-07-06 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('mental_health', 'Mental wellbeing'), ('exercise', 'Movement'), ('precaution', 'Precaution')], max_length=20)),
                ('trimester', models.CharField(choices=[('first', 'First trimester'), ('second', 'Second trimester'), ('third', 'Third trimester'), ('all', 'Any stage')], max_length=10)),
                ('text', models.TextField()),
                ('avoid_if_allergic_to', models.JSONField(blank=True, default=list)),
                ('avoid_if_condition', models.JSONField(blank=True, default=list)),
                ('avoid_if_diet', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('personalized_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_wellness.wellnesstip')),
                ('mental_health_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_wellness.wellnesstip')),
                ('nutrition_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_wellness.wellnesstip')),
                ('precaution_tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='daily_wellness.wellnesstip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
