# Generated by Django 4.2.14 on 2026-07-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellnesslog',
            name='only_if_condition',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
