# Generated by Django 4.2.14 on 2026-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_wellness', '0002_dailywellnesslog_only_if_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='exercise_tip',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='mental_health_tip',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='nutrition_tip',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='only_if_condition',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='precaution_tip',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='dailywellnesslog',
            name='source_url',
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='exercise_tips',
            field=models.ManyToManyField(blank=True, related_name='+', to='daily_wellness.wellnesstip'),
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='mental_health_tips',
            field=models.ManyToManyField(blank=True, related_name='+', to='daily_wellness.wellnesstip'),
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='nutrition_tips',
            field=models.ManyToManyField(blank=True, related_name='+', to='daily_wellness.wellnesstip'),
        ),
        migrations.AddField(
            model_name='dailywellnesslog',
            name='precaution_tips',
            field=models.ManyToManyField(blank=True, related_name='+', to='daily_wellness.wellnesstip'),
        ),
        migrations.AddField(
            model_name='wellnesstip',
            name='only_if_condition',
            field=models.JSONField(blank=True, default=list, help_text='If set, tip ONLY shows to mothers with at least one of these conditions (e.g. a gestational-diabetes-specific tip).'),
        ),
        migrations.AddField(
            model_name='wellnesstip',
            name='source_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
