# Generated by Django 4.2.14 on 2026-07-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('condition', models.CharField(choices=[('mood_dip', 'Mood has dipped'), ('mood_improved', 'Mood has improved'), ('mood_stable', 'Mood is steady'), ('no_recent_mood_log', "Hasn't logged mood recently"), ('no_stress_test_taken', 'Never taken a stress test'), ('stress_test_overdue', 'Stress test overdue'), ('high_risk_latest', 'Latest test showed high risk'), ('moderate_risk_latest', 'Latest test showed moderate risk'), ('worsening_risk_trend', 'Risk trending upward across tests'), ('consistent_logging', 'Logging consistently'), ('general', 'General / fallback')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('caution', 'Caution'), ('positive', 'Positive')], default='info', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('action_target', models.CharField(blank=True, choices=[('mood-checkin', 'Mood Check-in'), ('psychometric-select', 'Stress Test'), ('daily-plan', "Today's Wellness Plan"), ('wellness-chat', 'Ask Meri Aama'), ('forum-list', 'Community Forum'), ('', 'No link')], max_length=30)),
                ('action_label', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['condition'],
            },
        ),
    ]
